name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install openssl
      run: dnf -y install openssl openssl-devel
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Install RPM build tool
      uses: actions-rs/install@v0.1.2
      with:
        crate: cargo-generate-rpm
    - name: Package RPM
      run: cargo generate-rpm
    - name: Upload RPM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ruuth-rpm
        path: target/generate-rpm/*.rpm
    - name: Install DEB build tool
      uses: actions-rs/install@v0.1.2
      with:
        crate: cargo-deb
    - name: Package DEB
      run: cargo deb
    - name: Upload DEB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ruuth-deb
        path: target/debian/*.deb
